# Generated by Django 6.0.1 on 2026-02-03 12:39

import user.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='nip',
            field=models.CharField(max_length=10, null=True, validators=[user.validators.validate_nip]),
        ),
    ]
