# Generated by Django 6.0.1 on 2026-02-18 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_companyprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='deletion_reason',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
