# Generated by Django 6.0.1 on 2026-03-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_myuser_deleted_at_myuser_deletion_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
